services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - "discovery.type=single-node"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  async_api:
    container_name: async_api
    build:
      context: src
      dockerfile: ../Dockerfile
    restart: always
    depends_on:
      - elasticsearch
      - redis
    ports:
      - 8000:8000
    env_file:
      - src/core/.env

  test:
    container_name: test_api
    build:
      context: tests
    restart: always
    depends_on:
      - elasticsearch
      - redis
      - async_api
    entrypoint: >
      sh -c "pip install -r /tests/functional/requirements.txt
      && python3 /tests/functional/utils/wait_for_es.py
      && python3 /tests/functional/utils/wait_for_redis.py
      && pytest /tests/functional/src"

  redis:
    container_name: redis_test
    image: redis:6.2.6
    ports:
      - 6379:6379

volumes:
  elasticdata: